# Generated by Django 5.2.17 on 2026-10-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_drop_palette'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discoverable',
            field=models.BooleanField(default=True, verbose_name='others on Shajara can find me by name'),
        ),
    ]
