# Generated by Django 5.2.17 on 2026-10-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_discoverable'),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="discoverable",
            field=models.BooleanField(default=True, verbose_name="others on Silai Rahm can find me by name"),
        ),
        migrations.AddField(
            model_name='user',
            name='family_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='name of the family'),
        ),
        migrations.AddField(
            model_name='user',
            name='private_account',
            field=models.BooleanField(default=True, verbose_name='private account'),
        ),
        migrations.AddField(
            model_name='user',
            name='stories_audience',
            field=models.CharField(choices=[('public', 'Everyone on the site'), ('followers', 'My followers'), ('family', 'Only family members')], default='family', max_length=10, verbose_name='who sees life stories, events and the album'),
        ),
        migrations.AddField(
            model_name='user',
            name='tree_audience',
            field=models.CharField(choices=[('public', 'Everyone on the site'), ('followers', 'My followers'), ('family', 'Only family members')], default='followers', max_length=10, verbose_name='who sees my family tree'),
        ),
    ]
