# Generated by Django 5.2.17 on 2026-10-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_family_name_user_private_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='family_started',
            field=models.BooleanField(default=True),
        ),
    ]
