# Generated by Django 5.2.17 on 2026-10-06 16:54

import apps.genealogy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0007_stories_into_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recording',
            field=models.FileField(blank=True, upload_to=apps.genealogy.models.media_path, verbose_name='voice or video message'),
        ),
        migrations.AddField(
            model_name='media',
            name='in_story',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='media',
            name='kind',
            field=models.CharField(choices=[('photo', 'Photo'), ('document', 'Document'), ('audio', 'Voice recording'), ('video', 'Video')], default='photo', max_length=10),
        ),
    ]
