# Generated by Django 5.2.17 on 2026-10-05 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genealogy', '0006_person_linked_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('relative', 'Relative'), ('friend', 'Friend')], default='relative', max_length=10)),
                ('sender_relation', models.CharField(blank=True, max_length=10)),
                ('share_trees', models.BooleanField(default=True)),
                ('befriend', models.BooleanField(default=False)),
                ('shared_memberships', models.JSONField(blank=True, default=list)),
                ('message', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Waiting for an answer'), ('accepted', 'Connected'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_received', to=settings.AUTH_USER_MODEL)),
                ('recipient_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='genealogy.person')),
                ('recipient_tree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_sent', to=settings.AUTH_USER_MODEL)),
                ('sender_anchor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='genealogy.person')),
                ('sender_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='genealogy.person')),
                ('sender_tree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'status'], name='network_con_recipie_badaf3_idx'), models.Index(fields=['sender', 'status'], name='network_con_sender__e0f7d6_idx')],
            },
        ),
        migrations.CreateModel(
            name='PersonMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='genealogy.person')),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='genealogy.person')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('first', 'second'), name='unique_person_match')],
            },
        ),
    ]
